name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Playground
        run: pnpm dev:build

      - name: Build
        run: pnpm build

  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

  release-build:
    if: |
      github.event_name == 'push' &&
      !contains(github.event.head_commit.message, 'chore')
    needs:
      - lint
      - build

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: yes | npx bumpp package.json
